version: "3"

services:
    express_starter_db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3308:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: express_starters
            MYSQL_USER: user
            MYSQL_PASSWORD: password 
        volumes:
            - express_starter_db:/var/lib/mysql

    express_starter_test_db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: express_starter_test
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        volumes:
            - express_starter_test_db:/var/lib/mysql

volumes:
    express_starter_db:
        driver: local
    express_starter_test_db:
        driver: local
